backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/assets/img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid
          "}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Post Feed Heading", name: "postsHeading", widget: "string", default: "Latest posts"}
          - {label: "Archive Link Text", name: "archiveButtonText", widget: "string", default: "See all posts"}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
